version: '2'

volumes:
  pg-data:
    driver: local

services:
  pg:
    image: sameersbn/postgresql:9.6-2
    ports:
      - "27001:5432"
    volumes:
      - pg-data:/var/lib/postgresql
    environment:
      - DEBUG=false
      - PG_PASSWORD=postgres
      - DB_USER=play
      - DB_PASS=playplay
      - DB_NAME=play_dev
      - DB_EXTENSION=moddatetime